### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by daimagine** [nmn/react-infinity#11]
Hi, could you help me with this error :
```
Uncaught TypeError: Cannot read property '__reactAutoBindMap'
```
this is my complete gist `https://gist.github.com/daimagine/529a5fc24cee094281f8`

By the way, thank you for your awesome react infinity

**Comment by nmn** [comment]
I'll do a little more digging to say for sure, but I think this is the problem:
```
<div className="row">
  { ReactInfinity({
      data: this.props.products, //Array of objects.
      elementWidth: 300, // Width of one element
      elementHeight: 300, // height of one element
      margin: 300,
      childComponent: ProductItem, 
      }) 
   }
</div>
```

Instead try this:
```
<div className="row">
  <ReactInfinity
      data={this.props.products}
      elementWidth={300}
      elementHeight={300}
      margin={300}
      childComponent={React.createFactory(ProductItem)}
      />
</div>
```

React Infinity doesn't export a factory function, but a normal React component, so you can't call it like a function.
It expects childComponent to be a factory function though. This seems to be documented incorrectly as well. This is due to change in React itself, and me trying to remain backwards compatible. I'm trying to find some time to fix this soon.

**Comment by daimagine** [comment]
Thanks for helping me out. Your example did works but I found another problem.
My cards is having a wide left margin and the transform css property looks like this:

`transform: translate(160px, 10px) scale(1);`

This is my updated gists again: `https://gist.github.com/daimagine/529a5fc24cee094281f8`
Thank you

**Comment by nmn** [comment]
The wide left margin can be caused by one of few reasons:
- You cards are being center aligned and you want left aligned, this can be fixed by setting `align: 'left'`
- The childComponent (Product Item) has some margin/ position: relative that is moving the cards in their containers. (Seems unlikely as I think you've given me the translate value for the childer Wrapper component
- Some other bug in React Infinity that I can't reproduce.

Try option 1 and tell me what happens. If that does not solve your problem and there is a real bug, please add the CSS for your Gist and I will try to reproduce the error again.

**Comment by daimagine** [comment]
Sorry for late response. Set `align:` value with `left` solved it. It works like a charm
I will close this issue and perhaps updating the docs that highlight `align` default value will be a great help.
Thank you for your support.

**Comment by nmn** [comment]
@daimagine you're welcome
