### ISSUE TITLE
Is there support for appending additional items?

### ISSUE THREAD

**Issue by killerswan** [nmn/react-infinity#6]
It looks like Infinity.js has an API for [appending](http://airbnb.github.io/infinity/#api-listview-methods) ListItems to the ListView.  Do you already have something like that here, just not documented yet, perhaps?  :D

**Comment by nmn** [comment]
Since React-Infinity is based on React, you can use it like any other React component. You can just re-render with a new set of data.

So, short answer : YES.

You can add or remove elements dynamically. And React-infinity will animate it by default with CSS animations. v2 will support much more customization.

**Comment by killerswan** [comment]
Ahhh, thanks! :)
